"""add cluster_sources association table

Revision ID: 49a65b6430d2
Revises: e20e3e3531c7
Create Date: 2025-06-19 21:49:36.975601

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "49a65b6430d2"
down_revision = "e20e3e3531c7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cluster_sources",
        sa.Column("embedding_id", sa.Integer(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["cluster_id"], ["clusters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["embedding_id"], ["embeddings.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("embedding_id", "cluster_id"),
    )
    op.create_index(
        "ix_cluster_sources_cluster_id", "cluster_sources", ["cluster_id"], unique=False
    )
    op.create_index(
        "ix_cluster_sources_embedding_id",
        "cluster_sources",
        ["embedding_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_cluster_sources_embedding_id", table_name="cluster_sources")
    op.drop_index("ix_cluster_sources_cluster_id", table_name="cluster_sources")
    op.drop_table("cluster_sources")
    # ### end Alembic commands ###
