"""change_platform_column_to_text

Revision ID: 9b94b8f14d4e
Revises: 49a65b6430d2
Create Date: 2025-06-20 10:08:57.993984

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9b94b8f14d4e"
down_revision = "49a65b6430d2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sources",
        "platform",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Text(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sources",
        "platform",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
