"""migrate to Postgres compatible types

Revision ID: aa517cb99003
Revises: 9b94b8f14d4e
Create Date: 2025-06-23 10:42:47.026677

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "aa517cb99003"
down_revision = "9b94b8f14d4e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
