"""Add server default and not null to source created_at

Revision ID: db38a70c4d6a
Revises: 75d0319ecb84
Create Date: 2025-06-19 15:50:31.944238

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "db38a70c4d6a"
down_revision = "75d0319ecb84"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sources_created_at"), table_name="sources")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_sources_created_at"), "sources", ["created_at"], unique=False
    )
    # ### end Alembic commands ###
