name: CI

on:
  push:
    branches: ["main", "master", "*" ]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Install test and lint tools
          pip install pytest flake8

      - name: Run tests
        run: pytest -q

      - name: Lint with flake8
        run: flake8 . 